services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  openmeteo:
    image: "ghcr.io/open-meteo/open-meteo"
    ports:
      - "8080:8080"
    volumes:
      - open-meteo-data:/app/data

  api:
    build: ./api
    ports:
      - "50051:50051"
    environment:
      API_VERSION: "v1"
      LOG_LEVEL: 30
    restart: on-failure
    depends_on:
      - openmeteo

  producer:
    build: ./pp
    environment:
      API_VERSION: "v1"
      API_HOST: "api"
      MODEL_VERSION: "0.1.0"
      RABBITMQ_HOST: "rabbitmq"
    restart: on-failure
    depends_on:
      - rabbitmq
      - api
    links:
      - rabbitmq

  consumer:
    build: ./pc
    ports:
      - "8090:8090"
    environment:
      AMQP_HOST: "rabbitmq"
      PG_DATABASE: "postgres"
    restart: on-failure
    depends_on:
      - postgres
      - rabbitmq
    links:
      - rabbitmq

volumes:
  postgres-data:
  open-meteo-data:
    external: true
    
