services:
  rabbitmq:
    image: "rabbitmq:4.1-rc-alpine"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  openmeteo:
    image: "ghcr.io/open-meteo/open-meteo"
    ports:
      - "8080:8080"
    volumes:
      - open-meteo-data:/app/data

  api:
    build: ./api
    ports:
      - "8000:80"
    restart: on-failure
    environment:
      OPEN_METEO_HOST: "openmeteo"
    depends_on:
      openmeteo:
        condition: service_started

  # producer:
  #   build: ./pp
  #   environment:
  #     API_HOST: "api"
  #     RABBITMQ_HOST: "rabbitmq"
  #     RESOLUTION: 0
  #   restart: on-failure
  #   depends_on:
  #     api:
  #       condition: service_started
  #     rabbitmq:
  #       condition: service_healthy

volumes:
  open-meteo-data:
    external: true
