version: "3"
services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      API_VERSION: "v1"
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
  cpp:
    build: ./cpp
    environment:
      API_VERSION: "v1"
      API_HOST: "api"
      RABBITMQ_HOST: "rabbitmq"
    restart: on-failure
    depends_on:
      - rabbitmq
      - api
    links:
      - rabbitmq
    
