version: "3"

services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  openmeteo:
    image: "ghcr.io/open-meteo/open-meteo"
    ports:
      - "8080:8080"
    volumes:
      - open-meteo-data:/app/data

  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      API_VERSION: "v1"
      OPEN_METEO_HOST: "openmeteo"
    restart: on-failure
    depends_on:
      - openmeteo

  # pp:
  #   build: ./pp
  #   environment:
  #     API_VERSION: "v1"
  #     API_HOST: "api"
  #     RABBITMQ_HOST: "rabbitmq"
  #     SLEEP_INTERVAL: "0.5"
  #   restart: on-failure
  #   depends_on:
  #     - rabbitmq
  #     - api
  #   links:
  #     - rabbitmq

volumes:
  open-meteo-data:
    external: true
    
