[model]
state_dict_filename = "model.pth"
features = [
    "Latitude",
    "Longitude",
    "Elevation",
    "CloudCover",
    "UTTimeHour",
    "MoonAlt",
    "MoonAz",
]

[meteo]
protocol = "http"
host = "openmeteo"
port = 8080
model = "ecmwf_ifs04"
max_oktas = 8
