# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import brightness_service_pb2 as brightness__service__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in brightness_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BrightnessServiceStub(object):
    """handles sky brightness prediction and pollution requests
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBrightnessObservation = channel.unary_unary(
                '/brightness.BrightnessService/GetBrightnessObservation',
                request_serializer=brightness__service__pb2.Coordinates.SerializeToString,
                response_deserializer=brightness__service__pb2.BrightnessObservation.FromString,
                _registered_method=True)
        self.GetPollution = channel.unary_unary(
                '/brightness.BrightnessService/GetPollution',
                request_serializer=brightness__service__pb2.Coordinates.SerializeToString,
                response_deserializer=brightness__service__pb2.Pollution.FromString,
                _registered_method=True)


class BrightnessServiceServicer(object):
    """handles sky brightness prediction and pollution requests
    """

    def GetBrightnessObservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPollution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrightnessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBrightnessObservation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBrightnessObservation,
                    request_deserializer=brightness__service__pb2.Coordinates.FromString,
                    response_serializer=brightness__service__pb2.BrightnessObservation.SerializeToString,
            ),
            'GetPollution': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPollution,
                    request_deserializer=brightness__service__pb2.Coordinates.FromString,
                    response_serializer=brightness__service__pb2.Pollution.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'brightness.BrightnessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('brightness.BrightnessService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BrightnessService(object):
    """handles sky brightness prediction and pollution requests
    """

    @staticmethod
    def GetBrightnessObservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brightness.BrightnessService/GetBrightnessObservation',
            brightness__service__pb2.Coordinates.SerializeToString,
            brightness__service__pb2.BrightnessObservation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPollution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brightness.BrightnessService/GetPollution',
            brightness__service__pb2.Coordinates.SerializeToString,
            brightness__service__pb2.Pollution.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
