/**
 * @fileoverview gRPC-Web generated client stub for ctts
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.12.4
// source: service/service.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as service_service_pb from '../service/service_pb';


export class ServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorRead = new grpcWeb.MethodDescriptor(
    '/ctts.Service/Read',
    grpcWeb.MethodType.UNARY,
    service_service_pb.ReadRequest,
    service_service_pb.ReadReply,
    (request: service_service_pb.ReadRequest) => {
      return request.serializeBinary();
    },
    service_service_pb.ReadReply.deserializeBinary
  );

  read(
    request: service_service_pb.ReadRequest,
    metadata: grpcWeb.Metadata | null): Promise<service_service_pb.ReadReply>;

  read(
    request: service_service_pb.ReadRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: service_service_pb.ReadReply) => void): grpcWeb.ClientReadableStream<service_service_pb.ReadReply>;

  read(
    request: service_service_pb.ReadRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: service_service_pb.ReadReply) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ctts.Service/Read',
        request,
        metadata || {},
        this.methodDescriptorRead,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ctts.Service/Read',
    request,
    metadata || {},
    this.methodDescriptorRead);
  }

  methodDescriptorView = new grpcWeb.MethodDescriptor(
    '/ctts.Service/View',
    grpcWeb.MethodType.UNARY,
    service_service_pb.ViewRequest,
    service_service_pb.ViewReply,
    (request: service_service_pb.ViewRequest) => {
      return request.serializeBinary();
    },
    service_service_pb.ViewReply.deserializeBinary
  );

  view(
    request: service_service_pb.ViewRequest,
    metadata: grpcWeb.Metadata | null): Promise<service_service_pb.ViewReply>;

  view(
    request: service_service_pb.ViewRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: service_service_pb.ViewReply) => void): grpcWeb.ClientReadableStream<service_service_pb.ViewReply>;

  view(
    request: service_service_pb.ViewRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: service_service_pb.ViewReply) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ctts.Service/View',
        request,
        metadata || {},
        this.methodDescriptorView,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ctts.Service/View',
    request,
    metadata || {},
    this.methodDescriptorView);
  }

}

