/**
 * @fileoverview gRPC-Web generated client stub for ctts
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.12.4
// source: service/service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.ctts = require('./service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ctts.ServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ctts.ServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ctts.ReadRequest,
 *   !proto.ctts.ReadReply>}
 */
const methodDescriptor_Service_Read = new grpc.web.MethodDescriptor(
  '/ctts.Service/Read',
  grpc.web.MethodType.UNARY,
  proto.ctts.ReadRequest,
  proto.ctts.ReadReply,
  /**
   * @param {!proto.ctts.ReadRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ctts.ReadReply.deserializeBinary
);


/**
 * @param {!proto.ctts.ReadRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ctts.ReadReply)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ctts.ReadReply>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ctts.ServiceClient.prototype.read =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ctts.Service/Read',
      request,
      metadata || {},
      methodDescriptor_Service_Read,
      callback);
};


/**
 * @param {!proto.ctts.ReadRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ctts.ReadReply>}
 *     Promise that resolves to the response
 */
proto.ctts.ServicePromiseClient.prototype.read =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ctts.Service/Read',
      request,
      metadata || {},
      methodDescriptor_Service_Read);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ctts.ViewRequest,
 *   !proto.ctts.ViewReply>}
 */
const methodDescriptor_Service_View = new grpc.web.MethodDescriptor(
  '/ctts.Service/View',
  grpc.web.MethodType.UNARY,
  proto.ctts.ViewRequest,
  proto.ctts.ViewReply,
  /**
   * @param {!proto.ctts.ViewRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ctts.ViewReply.deserializeBinary
);


/**
 * @param {!proto.ctts.ViewRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ctts.ViewReply)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ctts.ViewReply>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ctts.ServiceClient.prototype.view =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ctts.Service/View',
      request,
      metadata || {},
      methodDescriptor_Service_View,
      callback);
};


/**
 * @param {!proto.ctts.ViewRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ctts.ViewReply>}
 *     Promise that resolves to the response
 */
proto.ctts.ServicePromiseClient.prototype.view =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ctts.Service/View',
      request,
      metadata || {},
      methodDescriptor_Service_View);
};


module.exports = proto.ctts;

