// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/service.proto

package service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReadRequest struct {
	Brightness           string   `protobuf:"bytes,1,opt,name=brightness,proto3" json:"brightness,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{0}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetBrightness() string {
	if m != nil {
		return m.Brightness
	}
	return ""
}

type ReadReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadReply) Reset()         { *m = ReadReply{} }
func (m *ReadReply) String() string { return proto.CompactTextString(m) }
func (*ReadReply) ProtoMessage()    {}
func (*ReadReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{1}
}

func (m *ReadReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadReply.Unmarshal(m, b)
}
func (m *ReadReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadReply.Marshal(b, m, deterministic)
}
func (m *ReadReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadReply.Merge(m, src)
}
func (m *ReadReply) XXX_Size() int {
	return xxx_messageInfo_ReadReply.Size(m)
}
func (m *ReadReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadReply.DiscardUnknown(m)
}

var xxx_messageInfo_ReadReply proto.InternalMessageInfo

type ViewRequest struct {
	Lat                  string   `protobuf:"bytes,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  string   `protobuf:"bytes,2,opt,name=lng,proto3" json:"lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewRequest) Reset()         { *m = ViewRequest{} }
func (m *ViewRequest) String() string { return proto.CompactTextString(m) }
func (*ViewRequest) ProtoMessage()    {}
func (*ViewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{2}
}

func (m *ViewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewRequest.Unmarshal(m, b)
}
func (m *ViewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewRequest.Marshal(b, m, deterministic)
}
func (m *ViewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewRequest.Merge(m, src)
}
func (m *ViewRequest) XXX_Size() int {
	return xxx_messageInfo_ViewRequest.Size(m)
}
func (m *ViewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ViewRequest proto.InternalMessageInfo

func (m *ViewRequest) GetLat() string {
	if m != nil {
		return m.Lat
	}
	return ""
}

func (m *ViewRequest) GetLng() string {
	if m != nil {
		return m.Lng
	}
	return ""
}

type ViewReply struct {
	Brightness           string   `protobuf:"bytes,1,opt,name=brightness,proto3" json:"brightness,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewReply) Reset()         { *m = ViewReply{} }
func (m *ViewReply) String() string { return proto.CompactTextString(m) }
func (*ViewReply) ProtoMessage()    {}
func (*ViewReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{3}
}

func (m *ViewReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewReply.Unmarshal(m, b)
}
func (m *ViewReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewReply.Marshal(b, m, deterministic)
}
func (m *ViewReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewReply.Merge(m, src)
}
func (m *ViewReply) XXX_Size() int {
	return xxx_messageInfo_ViewReply.Size(m)
}
func (m *ViewReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewReply.DiscardUnknown(m)
}

var xxx_messageInfo_ViewReply proto.InternalMessageInfo

func (m *ViewReply) GetBrightness() string {
	if m != nil {
		return m.Brightness
	}
	return ""
}

func init() {
	proto.RegisterType((*ReadRequest)(nil), "ctts.ReadRequest")
	proto.RegisterType((*ReadReply)(nil), "ctts.ReadReply")
	proto.RegisterType((*ViewRequest)(nil), "ctts.ViewRequest")
	proto.RegisterType((*ViewReply)(nil), "ctts.ViewReply")
}

func init() {
	proto.RegisterFile("service/service.proto", fileDescriptor_e51e679f9ae460e2)
}

var fileDescriptor_e51e679f9ae460e2 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xc1, 0x4a, 0xc5, 0x30,
	0x10, 0x45, 0xdf, 0xd3, 0xa2, 0x74, 0xba, 0x50, 0x03, 0x42, 0x71, 0x21, 0x12, 0x10, 0x05, 0x35,
	0x45, 0xfd, 0x03, 0x3f, 0xa1, 0x82, 0x0b, 0x77, 0x6d, 0x1d, 0xd2, 0x40, 0x4c, 0x6a, 0x32, 0xad,
	0xf4, 0xef, 0x25, 0x6d, 0x23, 0xd9, 0xbd, 0x55, 0xc2, 0xe5, 0x5c, 0xee, 0x61, 0xe0, 0xd2, 0xa3,
	0x9b, 0x54, 0x87, 0xd5, 0xf6, 0x8a, 0xc1, 0x59, 0xb2, 0x2c, 0xeb, 0x88, 0x3c, 0x7f, 0x82, 0xa2,
	0xc6, 0xe6, 0xab, 0xc6, 0x9f, 0x11, 0x3d, 0xb1, 0x6b, 0x80, 0xd6, 0x29, 0xd9, 0x93, 0x41, 0xef,
	0xcb, 0xfd, 0xcd, 0xfe, 0x3e, 0xaf, 0x93, 0x84, 0x17, 0x90, 0xaf, 0xf8, 0xa0, 0x67, 0xfe, 0x0c,
	0xc5, 0x87, 0xc2, 0xdf, 0xd8, 0x3d, 0x87, 0x63, 0xdd, 0xd0, 0x56, 0x0a, 0xdf, 0x25, 0x31, 0xb2,
	0x3c, 0xda, 0x12, 0x23, 0xf9, 0x03, 0xe4, 0x6b, 0x65, 0xd0, 0xf3, 0xa1, 0xb1, 0x17, 0x84, 0xd3,
	0xf7, 0x55, 0x99, 0x3d, 0x42, 0x16, 0x76, 0xd9, 0x85, 0x08, 0xd6, 0x22, 0x51, 0xbe, 0x3a, 0x4b,
	0xa3, 0xa0, 0xb5, 0x0b, 0x74, 0x58, 0x89, 0x74, 0x22, 0x19, 0xe9, 0x7f, 0x09, 0xbe, 0x7b, 0xbb,
	0xfb, 0xbc, 0x95, 0x8a, 0xfa, 0xb1, 0x15, 0x9d, 0xfd, 0xae, 0x8c, 0x35, 0xc6, 0x1a, 0x72, 0x6a,
	0x52, 0x8d, 0xae, 0x02, 0x1c, 0xef, 0xd6, 0x9e, 0x2c, 0x87, 0x7b, 0xfd, 0x0b, 0x00, 0x00, 0xff,
	0xff, 0xe6, 0x09, 0xf0, 0x35, 0x51, 0x01, 0x00, 0x00,
}
